/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : -- Unnamed --
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_CONNECTTO                           0
#define GD_IPADDRESS                           1
#define GD_REALHOST_                           2
#define GD_ABORT                               3
#define GD_STATUS                              4

#define GDX_CONNECTTO                          0
#define GDX_IPADDRESS                          1
#define GDX_REALHOST_                          2
#define GDX_ABORT                              3
#define GDX_STATUS                             4

#define Project8_CNT 5

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *scr;
extern UBYTE                 *PubScreenName;
extern void                 *vi;
extern struct Window        *Project8Wnd;
extern struct Gadget        *Project8GList;
extern struct Gadget        *Project8Gadgets[5];
extern UWORD                 Project8Left;
extern UWORD                 Project8Top;
extern UWORD                 Project8Width;
extern UWORD                 Project8Height;
extern UBYTE                *Project8Wdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern UBYTE                 Project8GTypes[];
extern struct MyNewGadget    Project8NGad[];
extern ULONG                 Project8GTags[];


extern void Project8Render( void );
extern int OpenProject8Window( void );
extern void CloseProject8Window( void );
