#ifndef CONNECT_H
#define CONNECT_H

// Source machine generated by GadToolsBox V2.0b
#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_CONNECTTO                           0
#define GD_IPADDRESS                           1
#define GD_REALHOST_                           2
#define GD_ABORT                               3
#define GD_STATUS                              4

#define GDX_CONNECTTO                          0
#define GDX_IPADDRESS                          1
#define GDX_REALHOST_                          2
#define GDX_ABORT                              3
#define GDX_STATUS                             4

#define Project8_CNT 5


void __SAVE_DS__ __ASM__ Connect_To_Server_Child(void);

#endif /* CONNECT_H */