#ifndef FKEY_H
#define FKEY_H

/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : -- Unnamed --
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_F1                                  0
#define GD_F2                                  1
#define GD_F3                                  2
#define GD_F4                                  3
#define GD_F5                                  4
#define GD_F6                                  5
#define GD_F7                                  6
#define GD_F8                                  7
#define GD_F9                                  8
#define GD_F0                                  9
#define GD_MOD                                 10
#define GD_SAVEE                               11
#define GD_CANCELL                             12

#define Project2_CNT 13

#endif /* FKEY_H */
