name: Build

on:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository and submodules
        uses: actions/checkout@v7
        with:
          submodules: recursive

      # for debugging runner and builder container
      #- name: Show environment
      #  run: make -C src show_env

      - name: Build with VBCC, DEBUG enabled
        run: make -C src  docker-debug

      - name: Build with VBCC
        run: make -C src  docker-release

      - name: Build ibmcon.device with VASM
        run: make -C src  ibmcon

      - name: Tests
        run: make -C src  tests

      - name: Package LHA archives
        run: make -C src package

      - name: Upload LHA release packages
        uses: actions/upload-artifact@v7
        with:
          name: DCTelnet-LHA-${{ github.sha }}
          path: |
            build/DCTelnet.lha
            build/DCTelnet-debug.lha
          if-no-files-found: error
          retention-days: 60
