name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository and submodules
        uses: actions/checkout@v7
        with:
          submodules: recursive

      # for debugging runner and builder container
      #- name: Show environment
      #  run: make -C src show_env

      - name: Build with VBCC, DEBUG enabled
        run: make -C src  ci-debug

      - name: Build with VBCC
        run: make -C src  ci

      - name: Build ibmcon.device with VASM
        run: make -C src  ibmcon

      - name: Tests
        run: make -C src  tests

      - name: Upload non-release build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: DCTelnet-${{ github.sha }}
          path: |
            build/vbcc-68000-release/DCTelnet.68000
            build/vbcc-68020-release/DCTelnet.68020
          if-no-files-found: error
          retention-days: 60
